# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
