# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20170601_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserProfile'),
        ),
    ]
