# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20170602_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True),
        ),
    ]
