# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20170602_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingroutine',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
