# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20170614_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingroutine',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
