# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_auto_20170614_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='triggered_at_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
