# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_habit_triggered_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='triggered_at_time',
            field=models.TimeField(blank=True),
        ),
    ]
