# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_auto_20170615_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='triggered_at_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='triggered_at_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
