# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_habit_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='trigger',
            field=models.CharField(choices=[('After I', 'After I'), ('When I', 'When I'), ('Whenever I', 'Whenever I'), ('Before I', 'Before I')], default='After I', max_length=15),
        ),
    ]
