# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('habits', '0014_auto_20170712_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='existingroutine',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='habit',
            name='trigger',
            field=models.CharField(choices=[('Wenn ich...', 'Wenn ich...'), ('Bevor ich...', 'Bevor ich...'), ('Immer wenn ich...', 'Immer wenn ich...'), ('Jedes Mal wenn ich...', 'Jedes Mal wenn ich...'), ('Nachdem ich...', 'Nachdem ich...')], default='Nachdem ich...', max_length=15),
        ),
        migrations.AlterField(
            model_name='targetbehavior',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AddField(
            model_name='comment',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit_comments', to='habits.Habit'),
        ),
        migrations.AddField(
            model_name='habit',
            name='comments',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='habits.Comment'),
            preserve_default=False,
        ),
    ]
